@baseUrl=http://localhost:5000/api
@userUrl=http://localhost:5000/api/users
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODFhZGQyZTE5NGM1YmFmNGRjNGZjNiIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTY2OTU2MTg1NywiZXhwIjoxNzAxMTE4NzgzfQ.DRlLM-aL-cxOiqM8FKJ0ptAgPIz6b-A-iG1W4bQ1SJ8

### register the new user
POST {{userUrl}}/register
Content-Type: application/json

{
    "username": "test5",
    "password": "test1234",
    "password2": "test1234",
    "email": "test5@gmail.com"
}
###

### login the user
POST {{userUrl}}/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}
###

### get the user profile
GET {{userUrl}}/current
Content-Type: application/json
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODFhZGQyZTE5NGM1YmFmNGRjNGZjNiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2Njk3OTY5ODgsImV4cCI6MTcwMTM1MzkxNH0.gMMVSBbRePqypkQwtvG74mYRwFRZrIDOd4Nvh7KTS0I
###

### create a thread
POST {{baseUrl}}/threads
Content-Type: application/json
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODFhZGQyZTE5NGM1YmFmNGRjNGZjNiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2Njk3OTY5ODgsImV4cCI6MTcwMTM1MzkxNH0.gMMVSBbRePqypkQwtvG74mYRwFRZrIDOd4Nvh7KTS0I

{
    "title": "test thread 1"
}
###